#o tempo todo em segundos
startdelay: 30
#certifique-se que [interval] maior que [wait] ou igual
interval: 900
wait: 300
#Numero de players necessario para começar os desafios
playercount: 5
#ligá-lo mostrará o cronômetro na barra do chefe no lugar da mensagem
actiontimer:
  enable: false
#usa a mensagem do bossbar de cada Desafio e procura por %timer% nesse
  inbossmessage: false
  message: '&2Tempo: &e%timer% &2segundos restante'
bossbar: true
worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
top:
  enable: true
  message: '&6Top desafiantes no desafio %type%'
#Numero de rankings
rank: 3
message:
  title: '&2&lVocê ganhou'
# em challenges vc adiciona e remove desafios
# para habilitar e desabilitar
challenges:
  - consume
  - blockbreak
  - dropitem
  - fish
  - craft
  - forge
  - kill
  - trivia
  - mini
  - damage
consume:
  items:
    - 'COOKED_MUTTON'
    - 'COOKED_PORKCHOP'
    - 'COOKED_SALMON'
    - 'STEAK'
    - 'BAKED_POTATO'
    - 'COOKED_CHICKEN'
    - 'COOKED_COD'
    - 'COOKED_RABBIT'
    - 'POTATO'
    - 'BEEF'
    - 'CHICKEN'
    - 'MUTTON'
    - 'PORKCHOP'
    - 'RABBIT'
    - 'COD'
    - 'SALMON'
    - 'ENCHANTED_GOLDEN_APPLE'
    - 'GOLDEN_APPLE'
    - 'APPLE'
    - 'GOLDEN_CARROT'
    - 'BEETROOT'
    - 'BEETROOT_SOUP'
    - 'BREAD'
    - 'CARROT'
    - 'MUSHROOM_STEW'
    - 'RABBIT_STEW'
    - 'SUSPICIOUS_STEW'
    - 'DRIED_KELP'
    - 'MELON_SLICE'
    - 'POISONOUS_POTATO'
    - 'PUMPKIN_PIE'
    - 'SWEET_BERRIES'
    - 'COOKIE'
    - 'GLOW_BERRIES'
    - 'HONEY_BOTTLE'
    - 'ROTTEN_FLESH'
    - 'SPIDER_EYE'
    - 'TROPICAL_FISH'
  reward:
    - 'eco give %player% 100'
  rewardpercent:
    - '30%eco give %player% 100'
  reward2:
    - 'eco give %player% 100'
  reward5:
    - 'eco give %player% 100'
  sound:
    enable: false
    sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    volume: 1
    pitch: 1
  min: 1
  max: 5
  message:
    challenge: 
      - ' '
      - '                       &6&lDesafio Aleatório '
      - ' '
      - '&2&l[!] Primeiro player que &cComer &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio de &cComer&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cComer &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cComer&2&l!!'
blockbreak:
  items:
    - 'STONE'
    - 'COAL_ORE'
    - 'IRON_ORE'
    - 'COPPER_ORE'
    - 'GOLD_ORE'
    - 'REDSTONE_ORE'
    - 'DIAMOND_ORE'
    - 'EMERALD_ORE'
    - 'NETHER_QUARTZ_ORE'
    - 'ANCIENT_DEBRIS'
    - 'GRAVEL'
    - 'SAND'
    - 'CLAY'
    - 'DIRT'
    - 'GRASS_BLOCK'
    - 'PODZOL'
    - 'MYCELIUM'
    - 'SANDSTONE'
    - 'SOUL_SAND'
    - 'NETHERRACK'
    - 'END_STONE'
    - 'OBSIDIAN'
    - 'MOSSY_COBBLESTONE'
    - 'COBBLESTONE'
    - 'BRICKS'
    - 'NETHER_BRICKS'
    - 'POLISHED_GRANITE'
    - 'POLISHED_DIORITE'
    - 'POLISHED_ANDESITE'
    - 'POLISHED_BLACKSTONE'
    - 'BLACKSTONE'
    - 'BASALT'
    - 'CRIMSON_NYLIUM'
    - 'WARPED_NYLIUM'
    - 'QUARTZ_BLOCK'
    - 'PRISMARINE'
    - 'SEA_LANTERN'
    - 'END_STONE_BRICKS'
    - 'MAGMA_BLOCK'
    - 'PURPUR_BLOCK'
    - 'RED_NETHER_BRICKS'
    - 'SHROOMLIGHT'
    - 'GLOWSTONE'
    - 'NETHER_WART_BLOCK'
    - 'ANCIENT_DEBRIS'
    - 'PACKED_ICE'
    - 'BLUE_ICE'
    - 'CRYING_OBSIDIAN'
    - 'HONEY_BLOCK'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cQuebrar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio de &cQuebrar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cQuebrar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cQuebrar&2&l!!'
dropitem:
  items:
    - 'DIAMOND_PICKAXE'
    - 'IRON_SWORD'
    - 'BOW'
    - 'ARROW'
    - 'SHIELD'
    - 'BREAD'
    - 'TORCH'
    - 'WATER_BUCKET'
    - 'LAVA_BUCKET'
    - 'ENDER_PEARL'
    - 'DIAMOND_SHOVEL'
    - 'IRON_AXE'
    - 'COMPASS'
    - 'CLOCK'
    - 'MAGMA_BLOCK'
    - 'DIAMOND_BOOSTS'
    - 'IRON_INGOT'
    - 'STICK'
    - 'CRAFTING_TABLE'
    - 'FURNACE'
    - 'ANVIL'
    - 'ENDER_CHEST'
    - 'ENDER_EYE'
    - 'OBSIDIAN'
    - 'FLINT_AND_STEEL'
    - 'COBBLESTONE'
    - 'REDSTONE'
    - 'REDSTONE_TORCH'
    - 'DIAMOND'
    - 'GOLDEN_APPLES'
    - 'NAME_TAG'
    - 'SADDLE'
    - 'LEAD'
    - 'BONE'
    - 'STRING'
    - 'GUNPOWDER'
    - 'SLIME_BALL'
    - 'BLAZE_ROD'
    - 'GHAST_TEAR'
    - 'NETHER_WART'
    - 'MILK_BUCKET'
    - 'GOLDEN_CARROT'
    - 'PUMPKIN_PIE'
    - 'ENDER_CHEST'
    - 'LAPIS_LAZULI'
    - 'INK_SAC'
    - 'FEATHER'
    - 'LEATHER'
    - 'PAPER'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cDropar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio&r de &cDropar items&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cDropar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio&r de &cDropar&2&l!!'
fish:
  items:
    - 'COD'
    - 'SALMON'
    - 'TROPICAL_FISH'
    - 'PUFFERFISH'
    - 'BOW'
    - 'FISHING_ROD'
    - 'NAME_TAG'
    - 'SADDLE'
    - 'LILY_PAD'
    - 'BOWL'
    - 'LEATHER'
    - 'LEATHER_BOOTS'
    - 'ROTTEN_FLESH'
    - 'STICK'
    - 'STRING'
    - 'GLASS_BOTTLE'
    - 'BONE'
    - 'INK_SAC'
    - 'TRIPWIRE_HOOK'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 2
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cPescar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cPescar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cPescar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cPescar&2&l!!'
craft:
  items:
    - 'OAK_PLANKS'
    - 'STICK'
    - 'CRAFTING_TABLE'
    - 'WOODEN_PICKAXE'
    - 'WOODEN_AXE'
    - 'WOODEN_SHOVEL'
    - 'WOODEN_SWORD'
    - 'WOODEN_HOE'
    - 'TORCH'
    - 'FURNACE'
    - 'STONE_PICKAXE'
    - 'STONE_AXE'
    - 'STONE_SHOVEL'
    - 'STONE_SWORD'
    - 'STONE_HOE'
    - 'IRON_INGOT'
    - 'IRON_PICKAXE'
    - 'IRON_AXE'
    - 'IRON_SHOVEL'
    - 'IRON_SWORD'
    - 'IRON_HOE'
    - 'GOLD_INGOT'
    - 'GOLDEN_PICKAXE'
    - 'GOLDEN_AXE'
    - 'GOLDEN_SHOVEL'
    - 'GOLDEN_SWORD'
    - 'GOLDEN_HOE'
    - 'DIAMOND_PICKAXE'
    - 'DIAMOND_AXE'
    - 'DIAMOND_SHOVEL'
    - 'DIAMOND_SWORD'
    - 'DIAMOND_HOE'
    - 'BOW'
    - 'ARROW'
    - 'LEATHER_BOOTS'
    - 'LEATHER_CHESTPLATE'
    - 'LEATHER_LEGGINGS'
    - 'LEATHER_HELMET'
    - 'IRON_HELMET'
    - 'IRON_CHESTPLATE'
    - 'IRON_LEGGINGS'
    - 'IRON_BOOTS'
    - 'ENCHANTING_TABLE'
    - 'BED'
    - 'COMPASS'
    - 'BOOKSHELF'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cCraftar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cCraftar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cCraftar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCraftar&2&l!!'
forge:
  items:
    - 'IRON_INGOT'
    - 'GOLD_INGOT'
    - 'IRON_INGOT'
    - 'GOLD_INGOT'
    - 'COPPER_INGOT'
    - 'COPPER_INGOT'
    - 'IRON_INGOT'
    - 'GOLD_INGOT'
    - 'GLASS'
    - 'STONE'
    - 'BRICK'
    - 'NETHER_BRICK'
    - 'SMOOTH_STONE'
    - 'COOKED_CHICKEN'
    - 'COOKED_BEEF'
    - 'COOKED_PORKCHOP'
    - 'COOKED_COD'
    - 'COOKED_SALMON'
    - 'COOKED_MUTTON'
    - 'COOKED_RABBIT'
    - 'GLASS'
    - 'GREEN_DYE'
    - 'DRIED_KELP'
    - 'LIME_DYE'
    - 'CHARCOAL'
    - 'POPPED_CHORUS_FRUIT'
    - 'SPONGE'

  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge: 
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cForjar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cForjar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cForjar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cForjar&2&l!!'
kill:
  items:
    - 'zombie'
    - 'skeleton'
    - 'creeper'
    - 'spider'
    - 'enderman'
    - 'cave_spider'
    - 'blaze'
    - 'witch'
    - 'slime'
    - 'magma_cube'
    - 'husk'
    - 'stray'
    - 'phantom'
    - 'drowned'
    - 'silverfish'
    - 'shulker'
    - 'polar_bear'
    - 'iron_golem' 
    - 'zombified_piglin'
    - 'wither_skeleton'
    - 'strider'
    - 'pig'
    - 'cow'
    - 'chicken'
    - 'sheep'
    - 'wolf'
    - 'bee'
    - 'hoglin'
    - 'piglin'
    - 'piglin_brute'
    - 'strider'
    - 'snow_golem' 
    - 'endermite'

  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cMatar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cMatar Mobs&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cMatar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cMatar Mobs&2&l!!'
    
mini:
  items:
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
    - 'Luan'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 10
  replace:
    CAKE_SLICES_EATEN: 'EAT_CAKE_SLICE'
    BELL_RING: 'RING_BELL'
    ANIMALS_BRED: 'BRED_ANIMALS'
    CAULDRON_FILLED: 'FILL_CAULDRON'
    CHEST_OPENED: 'OPEN_CHEST'
    NOTEBLOCK_TUNED: 'TUNE_NOTEBLOCK'
    FLOWER_POTTED: 'PUT_FLOWER_IN_POT'
    DISPENSER_INSPECTED: 'OPEN_DISPENSER'
    DROPPER_INSPECTED: 'OPEN_DROPPER'
    ENDERCHEST_OPENED: 'OPEN_ENDERCHEST'
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &c%item% &2&l%num% vezes vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio &c%item%&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &c%item% &2&l%num% vezes vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cmini&2&l!!'
    
damage:
  items:
    - 'FALL'
    - 'BLOCK_EXPLOSION'
    - 'CONTACT'
    - 'CRAMMING'
    - 'DRAGON_BREATH'
    - 'DROWNING'
    - 'ENTITY_ATTACK'
    - 'ENTITY_EXPLOSION'
    - 'FALLING_BLOCK'
    - 'FIRE'
    - 'FIRE_TICK'
    - 'FLY_INTO_WALL'
    - 'FREEZE'
    - 'HOT_FLOOR'
    - 'LAVA'
    - 'LIGHTNING'
    - 'MAGIC'
    - 'POISON'
    - 'PROJECTILE'
    - 'SONIC_BOOM'
    - 'STARVATION'
    - 'SUFFOCATION'
    - 'THORNS'
    - 'WITHER'
    - 'VOID'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 2
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player que &cTomar Dano &2&l%num% vezes de %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cDano&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cTomar Dano &2&l%num% vezes de %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cDano&2&l!!'    

trivia:
# faça todas as respostas em lower case para funfar!!!!!!!
  nocap: true
#cancela o chat, pra evitar copiar resposta
  cancelchat: true
  reward:
    - 'eco give %player% 100'
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório de perguntas e curiosidades'
      - ' '
      -  '&2&l[!]&cCuriosidades&2&l %item% '
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cCuriosidades&2&l!!'
    bossbar: '&2&l[!]&cCuriosidades&2&l %item% '
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCuriosidades&2&l!!'
1:
  Q: 'what is the server name?'
  A:
    - 'who knows'
    - 'dont know'
#área de desafio personalizada
events:
  consumeevent:
    - consume
  blockbreakevent:
    - blockbreak
    - obsidian
  dropitemevent:
    - dropitem 
  fistevent:
    - fish 
  deathevent:
    - kill
  furnaceevent:
    - forge
  craftingevent:
    - craft
  damageevent:
    - damage
#também adicione na lista de desafios principal para ativar
list:
  - 'obsidian'
obsidian:
  items:
    - 'OBSIDIAN'
  reward:
    - 'eco give %player% 10'
  min: 5
  max: 10
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cQuebrar &2&l%num% obsidian vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio &cCorrida das obsidianas&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cQuebrar &2&l%num% obsidian vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCorrida das obsidianas&2&l!!'