#o tempo todo em segundos
startdelay: 30
#certifique-se que [interval] maior que [wait] ou igual
interval: 900
wait: 300
#Numero de players necessario para começar os desafios
playercount: 5
#ligá-lo mostrará o cronômetro na barra do chefe no lugar da mensagem
actiontimer:
  enable: false
#usa a mensagem do bossbar de cada Desafio e procura por %timer% nesse
  inbossmessage: false
  message: '&2Tempo: &e%timer% &2segundos restante'
bossbar: true
worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
top:
  enable: true
  message: '&6Top desafiantes no desafio %type%'
#Numero de rankings
rank: 3
message:
  title: '&2&lVocê ganhou'
# em challenges vc adiciona e remove desafios
# para habilitar e desabilitar
challenges:
  - consumir
  - quebrar
  - dropar
  - pescar
  - craftar
  - forjar
  - matar
  - trivia
  - mini
  - dano
consume:
  items:
    - 'CARNE_DE_CORDERO_COZIDA'
    - 'CARNE_DE_PORCO_COZIDA'
    - 'SALMÃO_COZIDO'
    - 'CARNE'
    - 'BATATA_ASSADA'
    - 'FRANGO_COZIDO'
    - 'BACALHAU_COZIDO'
    - 'COELHO_COZIDO'
    - 'BATATA'
    - 'CARNE_VACA'
    - 'FRANGO'
    - 'CORDERO'
    - 'CARNE_DE_PORCO'
    - 'COELHO'
    - 'BACALHAU'
    - 'SALMÃO'
    - 'MAÇÃ_DOURADA_ENCANECADA'
    - 'MAÇÃ_DOURADA'
    - 'MAÇÃ'
    - 'CENOURA_DOURADA'
    - 'BETERRABA'
    - 'SOPA_DE_BETERRABA'
    - 'PÃO'
    - 'CENOURA'
    - 'ENSOPADO_DE_COGUMELO'
    - 'ENSOPADO_DE_COELHO'
    - 'ENSOPADO_SUSPICIOSO'
    - 'ALGA_SECA'
    - 'FATIA_DE_MELÃO'
    - 'BATATA_VENENOSA'
    - 'TORTA_DE_ABÓBORA'
    - 'BERRIES_DOCES'
    - 'BISCOITO'
    - 'BERRIES_FOSFORESCENTES'
    - 'GARFADA_DE_MEL'
    - 'CARNE_DECOMPOSTA'
    - 'OLHO_DE_ARANHA'
    - 'PEIXE_TROPICAL'
  reward:
    - 'eco give %player% 100'
  rewardpercent:
    - '30%eco give %player% 100'
  reward2:
    - 'eco give %player% 100'
  reward5:
    - 'eco give %player% 100'
  sound:
    enable: false
    sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'
    volume: 1
    pitch: 1
  min: 1
  max: 5
  message:
    challenge: 
      - ' '
      - '                       &6&lDesafio Aleatório '
      - ' '
      - '&2&l[!] Primeiro player que &cComer &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio de &cComer&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cComer &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cComer&2&l!!'
blockbreak:
  items:
    - 'PEDRA'
    - 'MINÉRIO_DE_CARBONO'
    - 'MINÉRIO_DE_FERRO'
    - 'MINÉRIO_DE_COPPER'
    - 'MINÉRIO_DE_OURO'
    - 'MINÉRIO_DE_REDSTONE'
    - 'MINÉRIO_DE_DIAMANTE'
    - 'MINÉRIO_DE_EMERALDA'
    - 'MINÉRIO_DE_QUARTZO_DO_NETHER'
    - 'DEBRIS_ANTIGO'
    - 'CASCALHO'
    - 'AREIA'
    - 'BARRO'
    - 'TERRA'
    - 'BLOCO_DE_GRAMA'
    - 'PODZOL'
    - 'MYCELIUM'
    - 'ARENITO'
    - 'AREIA_DE_ALMA'
    - 'NETHERRACK'
    - 'BLOCO_DE_FIM'
    - 'OBSIDIAN'
    - 'PEDRA_COBERTA_DE_MOFO'
    - 'PEDRA'
    - 'TIJOLOS'
    - 'TIJOLOS_DO_NETHER'
    - 'GRANITO_POLIDO'
    - 'DIORITO_POLIDO'
    - 'ANDESITO_POLIDO'
    - 'PEDRA_PRETA_POLIDA'
    - 'PEDRA_PRETA'
    - 'BASALTO'
    - 'NYLIUM_CRIMSON'
    - 'NYLIUM_WARPED'
    - 'BLOCO_DE_QUARTZO'
    - 'PRISMARINE'
    - 'LANTERNA_DO_MAR'
    - 'TIJOLOS_DE_PEDRA_DO_FIM'
    - 'BLOCO_DE_MAGMA'
    - 'BLOCO_PURPUR'
    - 'TIJOLOS_VERMELHOS_DO_NETHER'
    - 'SHROOMLIGHT'
    - 'GLOWSTONE'
    - 'BLOCO_DE_FUNGOS_DO_NETHER'
    - 'DEBRIS_ANTIGO'
    - 'GELO_COMPACTADO'
    - 'GELO_AZUL'
    - 'OBSIDIAN_CHORANDO'
    - 'BLOCO_DE_MEL'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cQuebrar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio de &cQuebrar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cQuebrar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cQuebrar&2&l!!'
dropitem:
  items:
    - 'PICARETA_DE_DIAMANTE'
    - 'ESPADA_DE_FERRO'
    - 'ARCO'
    - 'FLECHA'
    - 'ESCUDO'
    - 'PÃO'
    - 'TOCHA'
    - 'BALDE_DE_AGUA'
    - 'BALDE_DE_LAVA'
    - 'PEROLA_DO_FIM'
    - 'PÁ_DE_DIAMANTE'
    - ' MACHADO_DE_FERRO'
    - 'COMPASSO'
    - 'RELÓGIO'
    - 'BLOCO_DE_MAGMA'
    - 'BOTAS_DE_DIAMANTE'
    - 'LINGOTE_DE_FERRO'
    - 'BASTÃO'
    - 'MESA_DE_CRAFTING'
    - 'FORNO'
    - 'BIGORNA'
    - 'BAÚ_DO_FIM'
    - 'OLHO_DO_FIM'
    - 'OBSIDIAN'
    - 'ISQUEIRO'
    - 'PEDRA'
    - 'REDSTONE'
    - 'TOCHA_DE_REDSTONE'
    - 'DIAMANTE'
    - 'MAÇÃ_DOURADA'
    - 'TAGS_DE_NOME'
    - 'SELA'
    - 'CORDA'
    - 'OSSO'
    - 'FIO'
    - 'PÓ_DE_BOMBAS'
    - 'BOLA_DE_SLIME'
    - 'VARA_DE_BLAZE'
    - 'LÁGRIMA_DE_GHAST'
    - 'ERVA_DO_NETHER'
    - 'BALDE_DE_LEITE'
    - 'CENOURA_DOURADA'
    - 'TORTA_DE_ABÓBORA'
    - 'BAÚ_DO_FIM'
    - 'LAPIS_LAZULI'
    - 'SACO_DE_TINTA'
    - 'PENA'
    - 'COURO'
    - 'PAPEL'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cDropar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio&r de &cDropar items&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cDropar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio&r de &cDropar&2&l!!'
fish:
  items:
    - 'BACALHAU'
    - 'SALMÃO'
    - 'PEIXE_TROPICAL'
    - 'PEIXE_BALÃO'
    - 'ARCO'
    - 'VARA_DE_PESCA'
    - 'TAGS_DE_NOME'
    - 'SELA'
    - 'LÍLIO'
    - 'TIGELA'
    - 'COURO'
    - 'BOTAS_DE_COURO'
    - 'CARNE_DECOMPOSTA'
    - 'BASTÃO'
    - 'FIO'
    - 'GARRAFA_DE_VIDRO'
    - 'OSSO'
    - 'SACO_DE_TINTA'
    - 'GANCHO_DE_FIOS'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 2
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cPescar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cPescar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cPescar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cPescar&2&l!!'
craft:
  items:
    - 'TÁBUAS_DE_MADEIRA'
    - 'GRAVETO'
    - 'MESA_DE_CRAFT'
    - 'PICARETA_DE_MADEIRA'
    - 'MACHADO_DE_MADEIRA'
    - 'PÁ_DE_MADEIRA'
    - 'ESPADA_DE_MADEIRA'
    - 'ENXADA_DE_MADEIRA'
    - 'TOCHA'
    - 'FORNO'
    - 'PICARETA_DE_PEDRA'
    - 'MACHADO_DE_PEDRA'
    - 'PÁ_DE_PEDRA'
    - 'ESPADA_DE_PEDRA'
    - 'ENXADA_DE_PEDRA'
    - 'LINGOTE_DE_FERRO'
    - 'PICARETA_DE_FERRO'
    - 'MACHADO_DE_FERRO'
    - 'PÁ_DE_FERRO'
    - 'ESPADA_DE_FERRO'
    - 'ENXADA_DE_FERRO'
    - 'LINGOTE_DE_OURO'
    - 'PICARETA_DE_OURO'
    - 'MACHADO_DE_OURO'
    - 'PÁ_DE_OURO'
    - 'ESPADA_DE_OURO'
    - 'ENXADA_DE_OURO'
    - 'PICARETA_DE_DIAMANTE'
    - 'MACHADO_DE_DIAMANTE'
    - 'PÁ_DE_DIAMANTE'
    - 'ESPADA_DE_DIAMANTE'
    - 'ENXADA_DE_DIAMANTE'
    - 'ARCO'
    - 'FLECHA'
    - 'BOTAS_DE_COURO'
    - 'PEITORAL_DE_COURO'
    - 'CALÇAS_DE_COURO'
    - 'ELMO_DE_COURO'
    - 'ELMO_DE_FERRO'
    - 'PEITORAL_DE_FERRO'
    - 'CALÇAS_DE_FERRO'
    - 'BOTAS_DE_FERRO'
    - 'MESA_DE_ENCANTAMENTO'
    - 'CAMA'
    - 'BUSSOLA'
    - 'ESTANTE_DE_LIVROS'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cCraftar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cCraftar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cCraftar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCraftar&2&l!!'
forge:
  items:
    - 'LINGOTE_DE_FERRO'
    - 'LINGOTE_DE_OURO'
    - 'LINGOTE_DE_FERRO'
    - 'LINGOTE_DE_OURO'
    - 'LINGOTE_DE_COBRE'
    - 'LINGOTE_DE_COBRE'
    - 'LINGOTE_DE_FERRO'
    - 'LINGOTE_DE_OURO'
    - 'VIDRO'
    - 'PEDRA'
    - 'TIJOLO'
    - 'TIJOLO_DO_NETHER'
    - 'PEDRA_LISA'
    - 'FRANGO_ASSADA'
    - 'CARNE_DE_VACA_ASSADA'
    - 'GALINHA_ASSADA'
    - 'BACALHAU_ASSADA'
    - 'SALMÃO_ASSADA'
    - 'OVELHA_ASSADA'
    - 'COELHO_ASSADA'
    - 'VIDRO'
    - 'TINTA_VERDE'
    - 'ALGA_SECA'
    - 'TINTA_LIMÃO'
    - 'CARVÃO'
    - 'CHAORUS_FRUTA'
    - 'ESPONGA'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge: 
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cForjar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cForjar&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cForjar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cForjar&2&l!!'
kill:
  items:
    - 'ZUMBI'
    - 'ESQUELETO'
    - 'CREEPER'
    - 'ARANHA'
    - 'ENDERMAN'
    - 'ARANHA_DE_CAVERNA'
    - 'BLAZE'
    - 'BRUXA'
    - 'SLIME'
    - 'CUBO_DE_MAGMA'
    - 'HUSK_ZUMBI'
    - 'ERRANTE'
    - 'FANTASMA'
    - 'AFOGADO'
    - 'PEIXE_PRATEADO'
    - 'SHULKER'
    - 'URSO_POLAR'
    - 'GOLEM_DE_FERRO'
    - 'PIGLIN_ZUMBIFICADO'
    - 'ESQUELETO_COM_WITHER'
    - 'LAVAGANTE'
    - 'PORCO'
    - 'VACA'
    - 'GALINHA'
    - 'OVELHA'
    - 'LOBO'
    - 'ABELHA'
    - 'HOGLIN'
    - 'PIGLIN'
    - 'PIGLIN_BRUTO'
    - 'STRIDER'
    - 'ENDERMITE'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 5
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cMatar &2&l%num% %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cMatar Mobs&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cMatar &2&l%num% %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cMatar Mobs&2&l!!'
    
mini:
  items:
    - 'PULAR'
    - 'TOCAR_SINO'
    - 'CRIAR_ANIMAIS'
    - 'FATIAS_DE_BOLO_COMIDAS'
    - 'ENCHER_CALDEIRÃO'
    - 'ABRIR_BAU'
    - 'BLOCO_DE_NOTAS_AJUSTADO'
    - 'VASO_DE_FLOR'
    - 'TROCA_COM_VILLAGER'
    - 'INSPECIONAR_DISPENSER'
    - 'INSPECIONAR_DROPPER'
    - 'ABRIR_ENDERCHEST'

  reward:
    - 'eco give %player% 100'
  min: 1
  max: 10
  replace:
    CAKE_SLICES_EATEN: 'COMER_FATIA_DE_BOLO'
    BELL_RING: 'TOCAR_SINO'
    ANIMALS_BRED: 'CRIAR_ANIMAIS'
    CAULDRON_FILLED: 'ENCHER_CALDEIRÃO'
    CHEST_OPENED: 'ABRIR_BAU'
    NOTEBLOCK_TUNED: 'AJUSTAR_BLOCO_DE_NOTAS'
    FLOWER_POTTED: 'VASO_DE_FLOR'
    DISPENSER_INSPECTED: 'ABRIR_DISPENSER'
    DROPPER_INSPECTED: 'ABRIR_DROPPER'
    ENDERCHEST_OPENED: 'ABRIR_ENDERCHEST'

  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &c%item% &2&l%num% vezes vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio &c%item%&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &c%item% &2&l%num% vezes vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cmini&2&l!!'
    
damage:
  items:
    - 'CAIR'
    - 'EXPLOSÃO_DE_BLOCO'
    - 'CONTATO'
    - 'COMPRESSÃO'
    - 'SOPRO_DO_DRAGÃO'
    - 'AFOGAMENTO'
    - 'ATAQUE_DE_ENTIDADE'
    - 'EXPLOSÃO_DE_ENTIDADE'
    - 'BLOCO_CAINDO'
    - 'FOGO'
    - 'TICK_DE_FOGO'
    - 'COLIDIR_COM_PAREDE'
    - 'CONGELAR'
    - 'CHÃO_QUENTE'
    - 'LAVA'
    - 'RELÂMPAGO'
    - 'MÁGICA'
    - 'VENENO'
    - 'PROJETIL'
    - 'EXPLOSÃO_SÔNICA'
    - 'FOME'
    - 'SUFOCAÇÃO'
    - 'ESPINHOS'
    - 'WITHER'
    - 'VAZIO'
  reward:
    - 'eco give %player% 100'
  min: 1
  max: 2
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player que &cTomar Dano &2&l%num% vezes de %item% vai ganhar!!'
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cDano&2&l!!'
    bossbar: '&2&l[!] Primeiro player que &cTomar Dano &2&l%num% vezes de %item% vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cDano&2&l!!'    

trivia:
# faça todas as respostas em lower case para funfar!!!!!!!
  nocap: true
#cancela o chat, pra evitar copiar resposta
  cancelchat: true
  reward:
    - 'eco give %player% 100'
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório de perguntas e curiosidades'
      - ' '
      -  '&2&l[!]&cCuriosidades&2&l %item% '
      - ' '
    winner: '&2&l%player% ganhou o &2&ldesafio de &cCuriosidades&2&l!!'
    bossbar: '&2&l[!]&cCuriosidades&2&l %item% '
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCuriosidades&2&l!!'
1:
  Q: 'what is the server name?'
  A:
    - 'who knows'
    - 'dont know'
#área de desafio personalizada
events:
  consumeevent:
    - consume
  blockbreakevent:
    - blockbreak
    - obsidian
  dropitemevent:
    - dropitem 
  fistevent:
    - fish 
  deathevent:
    - kill
  furnaceevent:
    - forge
  craftingevent:
    - craft
  damageevent:
    - damage
#também adicione na lista de desafios principal para ativar
list:
  - 'obsidian'
obsidian:
  items:
    - 'OBSIDIAN'
  reward:
    - 'eco give %player% 10'
  min: 5
  max: 10
  message:
    challenge:
      - ' '
      - '                       &6&lDesafio Aleatório'
      - ' '
      - '&2&l[!] Primeiro player a &cQuebrar &2&l%num% obsidian vai ganhar!!'
      - ' '
    winner: '&2&l%player% venceu o &2&ldesafio &cCorrida das obsidianas&2&l!!'
    bossbar: '&2&l[!] Primeiro player a &cQuebrar &2&l%num% obsidian vai ganhar!!'
    none: '&c&lNinguém ganhou o &2&ldesafio de &cCorrida das obsidianas&2&l!!'